QSYS_BUILD_DIR=../../build/qsys

QSYS_NAME=nios_setup
QSYS_SRC=${QSYS_NAME}.qsys
SOPCINFO_FILENAME=${QSYS_NAME}.sopcinfo
SOPCINFO_FILEPATH=${QSYS_BUILD_DIR}/${SOPCINFO_FILENAME}
QSYS_OUT_DIR=${QSYS_BUILD_DIR}/${QSYS_NAME}
QSYS_QIP=${QSYS_OUT_DIR}/synthesis/${QSYS_NAME}.qip
QSYS_OBJ=${QSYS_OUT_DIR} ${SOPCINFO_FILEPATH}

QSYS_GEN=qsys-generate
QSYS_GEN_FLAGS=--synthesis=VERILOG --output-directory="${QSYS_OUT_DIR}" --family="Cyclone 10 LP" --part=10CL025YU256I7G
