PNR_BUILD_DIR=../../../build/pnr

FPGA_FAMILY="Cyclone 10 LP"
FPGA_PART=10CL025YU256I7G

QUARTUS_SH=quartus_sh
PROJECT_NAME=hello_world
QUARTUS_SH_PREPARE_FLAGS=--prepare -f ${FPGA_FAMILY} -d ${FPGA_PART} -t top ${PROJECT_NAME}
QPF_FILE=${PNR_BUILD_DIR}/${PROJECT_NAME}.qpf

SRC_PATH=../../rtl
SRCS=$(wildcard ${SRC_PATH}/*.vhd ${SRC_PATH}/*.vhdl ${SRC_PATH}/*.v ${SRC_PATH}/*.sv)
TOP_LEVEL=top
FILES_TCL_FILENAME=files.tcl
FILES_TCL_FILEPATH=${PNR_BUILD_DIR}/${FILES_TCL_FILENAME}

QUARTUS_OBJ=${PNR_BUILD_DIR}/output_files
SOF_FILE=${QUARTUS_OBJ}/${PROJECT_NAME}.sof
